I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/park/rec_space.rpy", line 298, in script
    call screen continue_from_rec
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/screens_in_game.rpy", line 149, in execute
    screen continue_from_rec():
  File "game/screens_in_game.rpy", line 149, in execute
    screen continue_from_rec():
  File "game/screens_in_game.rpy", line 150, in execute
    imagebutton auto "park/choices/choice90_%s.png":
Exception: Imagebutton does not have a idle image. (auto='park/choices/choice90_%s.png').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/park/rec_space.rpy", line 298, in script
    call screen continue_from_rec
  File "C:\Users\Panko\Desktop\RenPy\renpy\ast.py", line 2203, in execute
    self.call("execute")
  File "C:\Users\Panko\Desktop\RenPy\renpy\ast.py", line 2191, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Panko\Desktop\RenPy\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 569, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\Panko\Desktop\RenPy\renpy\exports.py", line 3149, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\Panko\Desktop\RenPy\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\core.py", line 3344, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\core.py", line 3764, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\core.py", line 575, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\core.py", line 575, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\core.py", line 575, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\screen.py", line 438, in visit_all
    callback(self)
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\core.py", line 3764, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\screen.py", line 449, in per_interact
    self.update()
  File "C:\Users\Panko\Desktop\RenPy\renpy\display\screen.py", line 639, in update
    self.screen.function(**self.scope)
  File "game/screens_in_game.rpy", line 149, in execute
    screen continue_from_rec():
  File "game/screens_in_game.rpy", line 149, in execute
    screen continue_from_rec():
  File "game/screens_in_game.rpy", line 150, in execute
    imagebutton auto "park/choices/choice90_%s.png":
  File "C:\Users\Panko\Desktop\RenPy\renpy\ui.py", line 952, in _imagebutton
    idle = choice(idle, idle_image, "idle", required=True)
  File "C:\Users\Panko\Desktop\RenPy\renpy\ui.py", line 946, in choice
    raise Exception("Imagebutton does not have a %s image. (auto=%r)." % (name, auto))
Exception: Imagebutton does not have a idle image. (auto='park/choices/choice90_%s.png').

Windows-10-10.0.22000
Ren'Py 8.0.0.22040201n
Visually Daunting 0.01
Wed Apr 27 22:57:29 2022
