I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/park/park_intro.rpy", line 22, in script
    donovan "Good morning, or evening!  Where ever you are."
IOError: Couldn't find file 'ethan_treat.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/park/park_intro.rpy", line 22, in script
    donovan "Good morning, or evening!  Where ever you are."
  File "renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1249, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 901, in do_display
    **display_args)
  File "renpy/character.py", line 647, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 4025, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'ethan_treat.mp3'.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
Visually Daunting 0.01
Sun Mar 13 01:57:14 2022
