I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/park/first_chat.rpy", line 154, in script
    scene bg wizcord_stream_ease with fadein
  File "game/scripts/park/first_chat.rpy", line 154, in <module>
    scene bg wizcord_stream_ease with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/park/first_chat.rpy", line 154, in script
    scene bg wizcord_stream_ease with fadein
  File "renpy/ast.py", line 1439, in execute
    paired = renpy.python.py_eval(self.paired)
  File "renpy/python.py", line 2276, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2269, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/park/first_chat.rpy", line 154, in <module>
    scene bg wizcord_stream_ease with fadein
NameError: name 'fadein' is not defined

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
Visually Daunting 0.01
Sat Mar 12 21:15:02 2022
